### ISSUE TITLE
Bus Boarding at ~10000% at the First Stop of the Line

### ISSUE THREAD

**Issue by thomaschow19** [Vectorial1024/ExpressBusServices#13] opened 2022-03-25 17:38 UTC
Hi, I am not sure if this is expected behaviour, but this mod is causing bus to "un-bunch" very aggressively at the first stop of the line, often to "boarding" at ~10000%. 

It would be great if there is an option to lessen the unbunching intensity, or to toggle off the unbunching changes caused by this mod.

**Comment by thomaschow19** [comment] 2022-03-25 17:43
To elaborate further on this issue, what I was suggesting is perhaps separating the "unbunching behaviour" side of this mod with the "Stop skipping" side of this mod. Maybe a toggle in the settings?

**Comment by thomaschow19** [comment] 2022-03-25 17:50
![Screenshot 2022-03-26 at 01 49 30](https://user-images.githubusercontent.com/29773444/160174821-cc0f8588-2258-4d8d-bd57-c53b0e208dc7.png)

A screenshot of the ~10000% boarding bus at the first stop.

**Comment by Vectorial1024** [comment] 2022-03-26 04:19
I see that you are using IPT2, and that your city is a RHD/LHT. I also see you are using TMPE.

It is definitely unnatural to have buses saying "Boarding 10000%". But then, while I could think of several causes to this, I could not see any direct link to EBS.

1. Maybe you have too much vehicle count for that bus line, so every bus is just waiting at the ferry terminus 
2. IPT2 settings: unbunching/vehicle interval https://steamcommunity.com/workshop/filedetails/discussion/928128676/1290690926874876460/
3. This is a case of the Citizen Runaway Problem, and therefore you could try my other mod Public Transport Unstucker https://steamcommunity.com/sharedfiles/filedetails/?id=2774427140

You can try using the "remove vehicle" button by TMPE on this stuck bus, and see how it goes. If the next bus can depart successfully near 100%, it indicates that it is very likely the Citizen Runaway Problem messing with you, and you could try my other mod for the fix.

-----

Now that I think about it, there might be potential conflict with IPT2 regarding the vehicle interval thing, but I am not sure.

Besides, it might not be a good idea to disable unbunching altogether, because if you do that, this mod would only cause them to bunch even more closely (aside from their natural tendency to bunch together). Unless you somehow make sure it will not bunch so severely, e.g. vehicle count is low.

Leaving this open to see if there is a need to follow-up.

**Comment by thomaschow19** [comment] 2022-03-26 11:16
That's true. I am using IPT2 and TMPE as well. Its a RHD city.

I tried to isolate the issue by disabling one mod at a time, and it appears to go away when I disable the EBS mod (from game main menu -> content manager). This issue does not happen with just IPT2 and TMPE enabled. 

The IPT2 compatibility mod does not affect the occurrence of this issue. However, when choosing different modes in the EBS IPT2 compatibility mod, the "Boarding 10000%" will happen at the corresponding stops. If "First Principle" is chosen then the "Boarding 10000%" will only occur at the first stop, while if "Respect IPT2 unbunching" is chosen then "Boarding 10000%" will occur at all the stops that are set to unbunch in IPT2.

Maybe it is related to how EBS is communicating with IPT2 on how to unbunch?

**Comment by Vectorial1024** [comment] 2022-03-26 18:47
Well, at least one thing I can point out, your testing with the IPT2 plugin has confirmed that the IPT2 plugin is functioning correctly. The only thing that the plugin does is to read IPT2's config and tell the main mod when to unbunch and when not to. And as you can see, it is working correctly.

What is not working is how the main mod reacts when told about which IPT2 stop to unbunch.

I can quickly test this on my side, see if the same happens.

---

Edit: it seems that the same did not happen on my side. However I have observed buses resetting their unbunching counter to 0 and the count up to around 700%, and then the unbunching releases the bus and it departs correctly. This is a visual bug and does not affect functionality, so I will not be fixing that.

Then the next thing to try would be the load order. The idea is to try to make EBS load after IPT2.

I am still not confident about Load Order Mod, but you could perhaps try it. (https://steamcommunity.com/sharedfiles/filedetails/?id=2448824112) If you are on Windows, you will need to run their separate load order manager and make EBS load after IPT2.

If that does not work, you can always try the manual method:

1. Disable both
2. Restart game
3. Enable IPT2
4. Restart game
5. Enable EBS + EBS-IPT2
6. Restart game
7. Load save

If you use the manual method, I recommend also trying the Instant Return to Desktop mod (https://steamcommunity.com/sharedfiles/filedetails/?id=2037888659)

**Comment by dsedivec** [comment] 2022-03-30 00:53
I think I might be experiencing this as well.  I just updated EBS and EBS+IPT2 today from Steam, so I think I'm running latest.  I am, however, also running a _ton_ of other mods.

I have not seen 10000%—my buses despawn before they hit that—but I have seen 300–400% commonly.  Like OP, disabling EBS but leaving IPT2 enabled makes this go away for me.

I tried using Loading Order Mod with manually configured order values:

* 500: Harmony
* 700–720: TMPE, Node Controller, one other mod I can't remember right now
* 800: IPT2
* 810: EBS
* 820: EBS+IPT2 addon
* 830: Public transport unsticking
* 1000: Everything else

I _believe_ this means EBS will be loaded after IPT2.  I still experience the problem described above with this ordering.

One thing I have noticed is that a bus will go through the normal, relatively fast 0–100% "boarding" meter, then it will start over again saying "boarding" once again, but now the meter goes slower.  I think this second "boarding" I see is what normally says "unbunching in progress" when I have only IPT (no EBS) enabled.  Not sure if the change in the label is important.

Maybe important: my city is new and many of my bus lines, and particularly the terminus stations, have very few passengers waiting to be picked up.  Zero passengers waiting to board is common.

I _think_ this problem is worse when I set EBS to "aggressive" compared to the default "prudential" value, but that's just my feeling, I didn't measure it.

Let me know if you need me to run a debug version or pull anything out of logs, if it'd help diagnose this problem.

**Comment by Vectorial1024** [comment] 2022-03-30 05:03
> my buses despawn before they hit that

I do not have this problem because I use TMPE's "no despawn" settings. I like the extra challenge coming from no-despawn.

> but I have seen 300–400% commonly

This value is normal. In fact, when I was testing the set of mods on my side, I sometimes see that value reaching 700% before the bus depart. What is not normal is having that value reach too high eg 10000% in the initial screen-cap.

The higher value is supposedly what should happen if you allow unbunching only at termini: you get smoother bus journeys at the cost of stronger unbunching at termini.

> then it will start over again saying "boarding" once again

I have also seen this happening on my side. This UI would be controlled by IPT2, and I also believe this is supposed to be the IPT2 unbunching meter working "not as expected". But because this is strictly a visual bug (ie does not block unbunching etc), this will be a very low priority bug.

---

Again, the main problem here is NOT about the "boarding value" go above 100%. It is about **_the "boarding value" going very high e.g. 10000%_**.

It could be that everything is working correctly, but the bus distances are not good, so that it reaches 10000% without departing. "They just grid-lock themselves by themselves".

Before this mod was made, I had a city where a lot of cims were taking the bus but I did not want to add metros etc yet, and I was using IPT2, so what I did was to increase the bus count on the bus lines. Eventually I reached a point where literally no buses were moving, because I increased bus count on multiple lines and their unbunching completely blocked each other. Line 1 would unbunch, blocking line 2, yet line 1 is actually unbunching because another bus from line 1 is stuck because line 2 is unbunching somewhere down the bus path. Basically a deadlock but with extra steps. This was what I originally meant by "borderline unusable" and "increasing the efficiency of buses".

**Comment by dsedivec** [comment] 2022-03-30 05:28
> > but I have seen 300–400% commonly
> 
> This value is normal.
[...]

My apologies!  Didn't realize that was expected behavior.

I'm kind of new to the game, so I'm still playing with a lot of the defaults, including traffic despawning.  When using EBS with IPT2 and leaving despawning enabled, I'm getting IPT2 (I think this is IPT2) warning me over and over when the buses despawn, so I had assumed that it was a problem.

> > then it will start over again saying "boarding" once again
> 
> I have also seen this happening on my side. This UI would be controlled by IPT2, and I also believe this is supposed to be the IPT2 unbunching meter working "not as expected". But because this is strictly a visual bug (ie does not block unbunching etc), this will be a very low priority bug.
[...]

I understand completely.

PS: I just realized that I've also used your X4 civilian fleets mod.  Thank you very much for all the great mods you make. :)

**Comment by Vectorial1024** [comment] 2022-07-26 17:24
Hi there, I think this issue might be similar to #15, and we might have found a source to this problem + released a fix to it on Steam just now. You may just go and recheck whether there are problems now.

**Comment by Vectorial1024** [comment] 2022-07-28 14:01
Self note:

When testing for something else, it is found that this bug appears when using IPT2 with EBS.

**Comment by Vectorial1024** [comment] 2022-11-08 17:07
Latest update:

Thanks to community queries, I rechecked this problem in depth, and have successfully reproduced this problem + can explain the problem. Currently I believe this has something to do with how the IPT2 plugin is unintentionally interfering with how IPT2 handles unbunching and what not.

This will be a 2-part update:

- [x] Modify the main mod's infrastructure to "leave an opening" for customization
- [x] Update the IPT2 plugin to use this "opening" so that this bug is fixed fully

This has caused much confusion among IPT2 users for a long time, but this shall be done in this week.

**Comment by Vectorial1024** [comment] 2022-11-11 14:55
The update is released.

Therefore, closing this.

**Closed as completed by Vectorial1024** 2022-11-11 14:55 UTC
Labels: bug
